// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
  type,
  employee_id,
  table_id
) VALUES (
  $1, $2, $3
) RETURNING id
`

type CreateOrderParams struct {
	Type       OrderType   `db:"type"`
	EmployeeID pgtype.UUID `db:"employee_id"`
	TableID    pgtype.Text `db:"table_id"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.Type, arg.EmployeeID, arg.TableID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
