// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddOrderItemsBulk(ctx context.Context, arg AddOrderItemsBulkParams) error
	CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (pgtype.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetItemByID(ctx context.Context, id int32) (MenuItem, error)
	GetMenuItems(ctx context.Context, arg GetMenuItemsParams) ([]MenuItem, error)
	GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error)
	GetOrderItemByID(ctx context.Context, arg GetOrderItemByIDParams) (OrderItem, error)
	GetOrders(ctx context.Context, arg GetOrdersParams) ([]Order, error)
	GetTableByID(ctx context.Context, id string) (Table, error)
	GetTables(ctx context.Context, status TableStatus) ([]Table, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUsers(ctx context.Context, arg GetUsersParams) ([]User, error)
	UpdateOrderItemStatus(ctx context.Context, arg UpdateOrderItemStatusParams) error
	UpdateTableStatus(ctx context.Context, arg UpdateTableStatusParams) error
}

var _ Querier = (*Queries)(nil)
