// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetItemByID(ctx context.Context, id int32) (MenuItem, error)
	GetMenuItems(ctx context.Context, arg GetMenuItemsParams) ([]MenuItem, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUsers(ctx context.Context, arg GetUsersParams) ([]User, error)
}

var _ Querier = (*Queries)(nil)
